[package]
name = "rustpython-jit"
version = "0.1.2"
description = "Experimental JIT(just in time) compiler for python code."
authors = [ "RustPython Team" ]
repository = "https://github.com/RustPython/RustPython"
license = "MIT"
edition = "2021"

autotests = false

[dependencies]
rustpython-bytecode = { path = "../compiler/bytecode", version = "0.1.2" }

cranelift = "0.76.0"
cranelift-module = "0.76.0"
cranelift-jit = "0.76.0"
num-traits = "0.2"
libffi = "2.0.0"
thiserror = "1.0"

[dev-dependencies]
rustpython-derive = { path = "../derive", version = "0.1.2" }

approx = "0.5.1"

[[test]]
name = "integration"
path = "tests/lib.rs"
